import os

CPD_LBWS = [10, 21, 63, 126, 256]
CPD_DEFAULT_LBW = 21
BACKTEST_AVERAGE_BASIS_POINTS = [None, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
USE_KM_HYP_TO_INITIALISE_KC = True

CPD_PINNACLE_OUTPUT_FOLDER = lambda lbw: os.path.join(
    "src/data", f"pinnacle_cpd_{(lbw if lbw else 'none')}lbw"
)

CPD_PINNACLE_OUTPUT_FOLDER_DEFAULT = CPD_PINNACLE_OUTPUT_FOLDER(CPD_DEFAULT_LBW)

FEATURES_PINNACLE_FILE_PATH = lambda lbw: os.path.join(
    "src/data", f"pinnacle_cpd_{(lbw if lbw else 'none')}lbw.csv"
)

FEATURES_PINNACLE_FILE_PATH_DEFAULT = FEATURES_PINNACLE_FILE_PATH(CPD_DEFAULT_LBW)

PINNACLE_DATA_FOLDER = "dataset/CLCDATA/"
PINNACLE_DATA_CUT = "RAD"

PINNACLE_ASSETS = [
    "AN",
    "BN",
    "CA",
    "CC",
    "CN",
    "DA",
    "DT",
    "DX",
    "EN",
    "ER",
    "ES",
    "FB",
    "FN",
    "GI",
    "JN",
    "JO",
    "KC",
    "KW",
    "LB",
    "LX",
    "MD",
    "MP",
    "NK",
    "NR",
    "SB",
    "SC",
    "SN",
    "SP",
    "TY",
    "UB",
    "US",
    "XU",
    "XX",
    "YM",
    "ZA",
    "ZC",
    "ZF",
    "ZG",
    "ZH",
    "ZI",
    "ZK",
    "ZL",
    "ZN",
    "ZO",
    "ZP",
    "ZR",
    "ZT",
    "ZU",
    "ZW",
    "ZZ",
]

# TODO get rid of the ones not used get
PINNACLE_ASSET_CLASS_MAPPING = {
    "TY": "FI",
    "US": "FI",
    "FB": "FI",
    "UB": "FI",
    "DT": "FI",
    "ZA": "CM",
    "ZC": "CM",
    "ZG": "CM",
    "ZL": "CM",
    "ZW": "CM",
    "ZI": "CM",
    "ZP": "CM",
    "ZR": "CM",
    "ZZ": "CM",
    "KW": "CM",
    "ZT": "CM",
    "ZF": "CM",
    "ZK": "CM",
    "GI": "CM",
    "ZO": "CM",
    "ZH": "CM",
    "NR": "CM",
    "ZN": "CM",
    "ZU": "CM",
    "LB": "CM",
    "JO": "CM",
    "KC": "CM",
    "CC": "CM",
    "SB": "CM",
    "DA": "CM",
    "NK": "FX",
    "DX": "FX",
    "AN": "FX",
    "BN": "FX",
    "SN": "FX",
    "JN": "FX",
    "FN": "FX",
    "CN": "FX",
    "MP": "FX",
    "ER": "EQ",
    "XX": "EQ",
    "YM": "EQ",
    "ES": "EQ",
    "EN": "EQ",
    "SC": "EQ",
    "SP": "EQ",
    "MD": "EQ",
    "CA": "EQ",
    "XU": "EQ",
    "LX": "EQ",
    "AD": "FX",
    "AP": "FI",
    "AX": "EQ",
    "BC": "CM",
    "BG": "CM",
    "BO": "CM",
    "CB": "FX",
    "CL": "CM",
    "CT": "CM",
    "C_": "CM",
    "FA": "FI",
    "FC": "CM",
    "FX": "FX",
    "GC": "CM",
    "GS": "FI",
    "HG": "CM",
    "HO": "CM",
    "HS": "EQ",
    "LC": "CM",
    "LH": "CM",
    "MW": "CM",
    "NG": "CM",
    "O_": "CM",
    "PA": "CM",
    "PL": "CM",
    "RB": "CM",
    "SF": "FX",
    "SI": "CM",
    "SM": "CM",
    "S_": "CM",
    "TA": "FI",
    "TD": "FI",
    "TU": "FI",
    "UA": "FI",
    "W_": "CM",
    "ZB": "CM",
    "ZM": "CM",
    "ZS": "CM",
}
